# Generated by Django 5.2.9 on 2025-12-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('Deadline_in_mnths', models.IntegerField()),
                ('lastYearResolutionSatus', models.CharField(max_length=150)),
                ('lastYearAchievements', models.CharField(max_length=250)),
            ],
        ),
    ]
